steps:
  - id: "Executando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f','docker-compose.yaml', 'up','-d']

  - id: "Rodando go unit test"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','go','test','/go/bin/app']





